name: Generate Dataset

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas geopandas shapely

      - name: Run script
        run: |
          printf "1\n22\n3\ny\ngeoJson/id.json\n10\n1\n" | python3 file_generator.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: datasets
          path: |
            *.csv
            *.xlsx
