name: Generate Dataset

on:
  workflow_dispatch:
    inputs:
      format_choice:
        description: 'Choose format: 1 for WKT, 2 for GeoJSON'
        required: true
        default: '1'
      num_columns:
        description: 'Enter number of columns (max 22)'
        required: true
        default: '22'
      area_choice:
        description: 'Choose area: 1 for Jakarta, 2 for Yogyakarta, 3 for Indonesia, 4 for Japan, 5 for Vietnam'
        required: true
        default: '3'
      use_districts:
        description: 'Use actual district geometries for Jakarta? (y/n) [only for area 1]'
        required: false
        default: 'n'
      district_geojson_path:
        description: 'Enter path to GeoJSON file for Jakarta districts (e.g., geoJson/jakarta_districts.json)'
        required: false
        default: ''
      use_land_boundaries:
        description: 'Use land boundaries to avoid sea areas? (y/n) [only for areas 3, 4, 5]'
        required: false
        default: 'n'
      land_geojson_path:
        description: 'Enter path to GeoJSON file for land boundaries (e.g., geoJson/id.json)'
        required: false
        default: ''
      num_rows:
        description: 'Enter number of rows'
        required: false
        default: '10'
      geometry_type:
        description: 'Choose geometry type: 1 for POINT, 2 for POLYGON, 3 for MULTIPOLYGON'
        required: false
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas geopandas shapely

      - name: Prepare inputs and run script
        run: |
          # Initialize empty input file
          echo -n "" > inputs.txt

          # Always include format_choice, num_columns, and area_choice first
          echo "${{ inputs.format_choice }}" >> inputs.txt
          echo "${{ inputs.num_columns }}" >> inputs.txt
          echo "${{ inputs.area_choice }}" >> inputs.txt

          # Handle conditional inputs based on area_choice
          if [ "${{ inputs.area_choice }}" = "1" ]; then
            echo "${{ inputs.use_districts }}" >> inputs.txt
            if [ "${{ inputs.use_districts }}" = "y" ]; then
              echo "${{ inputs.district_geojson_path }}" >> inputs.txt
              if [ -z "${{ inputs.district_geojson_path }}" ]; then
                echo "Error: district_geojson_path is required when use_districts is 'y'" >&2
                exit 1
              fi
            else
              echo "${{ inputs.num_rows }}" >> inputs.txt
              echo "${{ inputs.geometry_type }}" >> inputs.txt
              if [ -z "${{ inputs.num_rows }}" ] || [ -z "${{ inputs.geometry_type }}" ]; then
                echo "Error: num_rows and geometry_type are required when use_districts is 'n'" >&2
                exit 1
              fi
            fi
          elif [ "${{ inputs.area_choice }}" = "2" ]; then
            echo "${{ inputs.num_rows }}" >> inputs.txt
            echo "${{ inputs.geometry_type }}" >> inputs.txt
            if [ -z "${{ inputs.num_rows }}" ] || [ -z "${{ inputs.geometry_type }}" ]; then
              echo "Error: num_rows and geometry_type are required for Yogyakarta" >&2
              exit 1
            fi
          elif [ "${{ inputs.area_choice }}" = "3" ] || [ "${{ inputs.area_choice }}" = "4" ] || [ "${{ inputs.area_choice }}" = "5" ]; then
            echo "${{ inputs.use_land_boundaries }}" >> inputs.txt
            if [ "${{ inputs.use_land_boundaries }}" = "y" ]; then
              echo "${{ inputs.land_geojson_path }}" >> inputs.txt
              if [ -z "${{ inputs.land_geojson_path }}" ]; then
                echo "Error: land_geojson_path is required when use_land_boundaries is 'y'" >&2
                exit 1
              fi
              echo "${{ inputs.num_rows }}" >> inputs.txt
              echo "${{ inputs.geometry_type }}" >> inputs.txt
            else
              echo "${{ inputs.num_rows }}" >> inputs.txt
              echo "${{ inputs.geometry_type }}" >> inputs.txt
            fi
            if [ -z "${{ inputs.num_rows }}" ] || [ -z "${{ inputs.geometry_type }}" ]; then
              echo "Error: num_rows and geometry_type are required for this area" >&2
              exit 1
            fi
          else
            echo "Error: Invalid area_choice" >&2
            exit 1
          fi

          # Debug: Display the input sequence
          echo "Input sequence:"
          cat inputs.txt

          # Run the script with the prepared inputs
          python3 file_generator.py < inputs.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datasets
          path: |
            *.csv
            *.xlsx
