name: Generate Dataset

on:
  workflow_dispatch:
    inputs:
      format_choice:
        description: 'Choose format: 1 for WKT, 2 for GeoJSON'
        required: true
        default: '1'
      num_columns:
        description: 'Enter number of columns (max 22)'
        required: true
        default: '22'
      area_choice:
        description: 'Choose area: 1 for Jakarta, 2 for Yogyakarta, 3 for Indonesia, 4 for Japan, 5 for Vietnam'
        required: true
        default: '3'
      geojson_path:
        description: 'Enter path to GeoJSON file for land boundaries (e.g., geojson/id-jk.min.geojson for Jakarta, geojson/id.json for Indonesia)'
        required: false
        default: ''
      num_rows:
        description: 'Enter number of rows'
        required: false
        default: '10'
      geometry_type:
        description: 'Choose geometry type: 1 for POINT, 2 for POLYGON, 3 for MULTIPOLYGON'
        required: false
        default: '1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pandas geopandas shapely openpyxl tqdm

      - name: Prepare inputs and run script
        run: |
          # Initialize empty input file
          echo -n "" > inputs.txt

          # Always include format_choice, num_columns, and area_choice
          echo "${{ inputs.format_choice }}" >> inputs.txt
          echo "${{ inputs.num_columns }}" >> inputs.txt
          echo "${{ inputs.area_choice }}" >> inputs.txt

          # Handle GeoJSON path for areas 1, 3, 4, 5
          if [ "${{ inputs.area_choice }}" = "1" ] || [ "${{ inputs.area_choice }}" = "3" ] || [ "${{ inputs.area_choice }}" = "4" ] || [ "${{ inputs.area_choice }}" = "5" ]; then
            echo "${{ inputs.geojson_path }}" >> inputs.txt
            if [ -z "${{ inputs.geojson_path }}" ]; then
              echo "Error: geojson_path is required for this area" >&2
              exit 1
            fi
          fi

          # Always include num_rows and geometry_type
          echo "${{ inputs.num_rows }}" >> inputs.txt
          echo "${{ inputs.geometry_type }}" >> inputs.txt
          if [ -z "${{ inputs.num_rows }}" ] || [ -z "${{ inputs.geometry_type }}" ]; then
            echo "Error: num_rows and geometry_type are required" >&2
            exit 1
          fi

          # Debug: Display the input sequence
          echo "Input sequence:"
          cat inputs.txt

          # Run the script with the prepared inputs
          python3 file_generator.py < inputs.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datasets
          path: |
            *.csv
            *.xlsx